@startuml Part2ClassDiagram
class Ship{
    #shipName : String 
    #yearBuilt : String 
    +setShipName(shipName : String) : void
    +getShipName() : String
    +setyearBuilt(yearBuilt : String) : void
    +getYearBuilt() : String
    +toString() : String
}
class CruiseShip extends Ship{
    -maxNumberPassengers : int
    +setMaxNumberPassengers(maxNumberPassengers : int) : void
    +getMaxNumberPassengers() : int
    +toString() : String
}
class CargoShip extends Ship{
    -cargoCapacityInTonnage : int
    +setcargoCapacityInTonnage(cargoCapacityInTonnage : int) : void
    +getcargoCapacityInTonnage() : int
    +toString() : String
}
@enduml